location = /.well-known/openpgpkey {
    return 301 /.well-known/openpgpkey/;
}

location ^~ /.well-known/openpgpkey/ {
    proxy_pass http://127.0.0.1:__PORT__;
    include proxy_params_no_auth;
    proxy_buffering off;
    default_type application/octet-stream;
    add_header Access-Control-Allow-Origin * always;
}

location / {
    proxy_pass http://127.0.0.1:__PORT__;
    include proxy_params_with_auth;
}
