#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_restore "$install_dir"
ynh_restore "$data_dir"
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"

ynh_systemctl --service=nginx --action=reload
ynh_systemctl --service="$app" --action=restart
